image: Visual Studio 2015
platform: x64
shallow_clone: true

install:
  - set PATH=C:\projects\opencv\x64\vc14\bin;%PATH%
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x86_amd64
  - set QTDIR=C:\Qt\5.11\msvc2015_64
  - '%QTDIR%\bin\qtenv2.bat'
  - qmake -v

build_script:
  - mkdir C:\projects\nbody\build-release
  - cd C:\projects\nbody\build-release
  - qmake ..\nbody.pro CONFIG+=release CONFIG+=NO_UI
  - call C:\Qt\Tools\QtCreator\bin\jom

after_build:
  - 7z a C:\projects\nbody\build-release.zip C:\projects\nbody\build-release

test_script:
  - set PATH=C:\projects\nbody\build-release\lib;%PATH%
  - test\engine\engine
  - test\solver\solver
  - test\solvers_equality\solvers_equality

#artifacts:
  #- path: build-release.zip

deploy: off


