name: Ubuntu@Colab+CUDA

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: ubuntu-20.04
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: info
      run: |
        cat /proc/cpuinfo | egrep "model name"
        gcc --version
        /usr/local/cuda/bin/nvcc --version

    - name: build
      run: .github/workflows/ubuntu-gpu-build.sh
